version: '3.1'
services:
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: blacklistd
      MYSQL_DATABASE: blacklistd
      MYSQL_USER: blacklistd
      MYSQL_PASSWORD: blacklistd
